### ISSUE TITLE
Hydra\Modules\Loot-Loot.lua:35: attempt to compare nil with number

### ISSUE THREAD

**Issue by kittykatmax** [Phanx/Hydra#18] opened 2015-08-26 21:37 UTC
Hope this is helpful...copied from bugsack.  This popped from freshly installed, totally clean Hydra version 6.2.0.31 downloaded via Curse Client :

```
15x Hydra\Modules\Loot-Loot.lua:35: attempt to compare nil with number
Hydra\Modules\Loot-Loot.lua:35: in function `OnStateChange'
Hydra\Core.lua:343: in function `?'
Hydra\Core.lua:248: in function <Hydra\Core.lua:248>

Locals:
self = <unnamed>
unit = nil
newstate = 3
(for generator) = <function> defined =[C]:-1
(for state) = <table>
(for control) = "Loot"
name = "Loot"
module = <unnamed>
enable = true
groupUnits = <table>
SOLO = 0
Hydra = <table>
INSECURE = 1
LEADER = 3
SECURE = 2
```

**Comment by hydra** [comment] 2015-08-27 13:44
@kittykatmax Please can you quote code that you past so I don't get notifications.

good:
```
SetupOptions = defined @Hydra\Core.lua:364
```

bad:

SetupOptions = defined @Hydra\Core.lua:364

**Comment by Phanx** [comment] 2015-08-27 21:06
Duplicate of #16

**Closed by Phanx** 2015-08-27 21:06 UTC
