### ISSUE TITLE
hydra addon refuses to sell junk or repair gear at vendor

### ISSUE THREAD

**Issue by kozmosis** [Phanx/Hydra#12] opened 2015-08-07 12:55 UTC
This only happens on my main and I have no clue why. Uninstall reinstall - reload UI - disable reenable addon - nothing works until it accidentaliy forgets to stop failing for no apparent reason months down the road. This has been occurring for years now and I have never seen anyone else mention it. works fine on every toon except main. extremely frustrating bug as this is the only reason I use this addon. So I guess I will just uninstall and use something else

**Comment by Phanx** [comment] 2015-08-07 21:30
If auto-repair is the only thing you're using Hydra for, yes, you should uninstall it and use any of the appromiately 49308432 addons that do nothing but auto-repair. You're using a bazooka to squash a single ant.

If you actually want to be helpful, unfortunately your ticket doesn't contain any information which would enable me to track down the cause of the problem, let alone fix it. You can find a list of information that should be included in a bug report, as well as instructions for gathering that info, here:

http://phanx.net/addons/help#report

However, I suspect you actually just wanted to complain and tell me you were uninstalling my addon, so I'm just going to go ahead and close this ticket.

**Closed by Phanx** 2015-08-07 21:30 UTC

**Comment by kozmosis** [comment] 2016-01-05 22:24
Phanx a lot man for your smart ass reply to my issue. It really made me
feel like you gave a shit about my concerns and about fixing your broken
addon. The auto-repair fail was not the only bug I noticed it was just the
only one I felt needed addressing. Theres also the inability to change the
loot settings but im sure theres 49308432 other addons that aren't buggy
pieces of crap that I can find. Already uninstalled your junk thanks for
the "advice". Take your shitty attitude and shove up your face you moron.
Good thing for you this is the internet where you can feel free to act like
a cunt to me without worrying about me stomping a fucking mudhole in your
ass. Fix your shitty addon and don't blame others for its crappiness, and
then go fuck off punk!
